name: 🧪

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-pages:
    name: Install and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
      - run: python3 -m pip install .[test]
      - run: python3 -m pytest test
        name: Run tests
