name: 🕶️ 

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: |
            python3 -m pip install -e .[style,docs]
      - run: python3 -m ruff .
        name: Run ruff checks
      - run: python3 -m flake8 .
        name: Run flake8 checks
      - run: python3 -m mypy .
        name: Run mypy checks --install-types
      - run: python3 -m isort --check .
        name: Run isort checks
      - run: |
          cd docs
          make html SPHINXOPTS="-W"
        name: Test docs build
