name: 🧪📦

on:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests-with-pip:
    name: Run tests with pyfax installed from pip
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
        with:
          ref: v2022.0.0
        name: Get latest pyfax version
      - run: rm -rf pyfax VERSION
        name: Remove downloaded pyfax
      - run: python3 -m pip install pyfax
        name: Install pyfax
      - run: pip install pytest
        name: Install pytest
      - run: python3 -m pytest test/
        name: Run unit tests
      - run: python3 -m pytest demo/test_demos.py
        name: Run demos

  run-tests-with-conda:
    name: Run tests with pyfax installed from conda-forge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: pyfax
      - uses: actions/checkout@v2
        with:
          ref: v2022.0.0
        name: Get latest pyfax version
      - run: rm -rf pyfax VERSION
        name: Remove downloaded pyfax
      - run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install pyfax
          conda install pytest
          pytest test/
          pytest demo/test_demos.py
        shell: bash -l {0}
        name: Install pyfax and run tests

  run-test-with-pypi-zip:
    name: Run tests with pyfax downloaded from PyPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          wget -O pyfax.tar.gz https://pypi.io/packages/source/s/pyfax/pyfax-2022.0.0.tar.gz
          tar -xvzf pyfax.tar.gz
        name: Download and unpack latest version of pyfax
      - run: pip install pytest
        name: Install pytest
      - run: |
          cd pyfax-2022.0.0
          pip install -r requirements.txt
          python3 -m pytest test/
        name: Install requirements, run tests and demos
