name: 🧪📦

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
    branches:
      - main

jobs:
  run-tests-with-pip:
    name: Run tests with pyfax installed from pip
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
        with:
          ref: v2022.6.4
        name: Get latest pyfax version
      - run: rm -rf pyfax VERSION
        name: Remove downloaded pyfax
      - run: python3 -m pip install pyfax
        name: Install pyfax
      - run: pip install pytest lipsum
        name: Install test requirements
      - run: python3 -m pytest test/
        name: Run unit tests

  run-test-with-pypi-zip:
    name: Run tests with pyfax downloaded from PyPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          wget -O pyfax.tar.gz https://pypi.io/packages/source/p/pyfax/pyfax-2022.6.4.tar.gz
          tar -xvzf pyfax.tar.gz
        name: Download and unpack latest version of pyfax
      - run: pip install pytest lipsum
        name: Install test requirements
      - run: |
          cd pyfax-2022.6.4
          pip install -r requirements.txt
          python3 -m pytest test/
        name: Install requirements, run tests and demos
