name: 🧪📦

on:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests-with-pip:
    name: Run tests with pyfax installed from pip
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
        with:
          ref: v2024.2.6
        name: Get latest pyfax version
      - run: rm -rf pyfax VERSION
        name: Remove downloaded pyfax
      - run: python3 -m pip install pyfax
        name: Install pyfax
      - run: python3 -m pip install pytest
        name: Install test requirements
      - run: python3 -m pytest test/
        name: Run unit tests

  run-test-with-pypi-zip:
    name: Run tests with pyfax downloaded from PyPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
        with:
          ref: v2024.2.6
        name: Get latest pyfax version
      - run: rm -rf pyfax VERSION
        name: Remove downloaded pyfax
      - run: |
          wget -O pyfax.tar.gz https://pypi.io/packages/source/p/pyfax/pyfax-2024.2.6.tar.gz
          tar -xvzf pyfax.tar.gz
        name: Download and unpack latest version of pyfax
      - run: python3 -m pip install pytest
        name: Install test requirements
      - run: |
          cd pyfax-2024.2.6
          python3 -m pip install requests feedparser pytest
          python3 -m pytest ../test/
        name: Install requirements, run tests and demos
