name: 🔢

on:
  push:
    branches:
      - main

jobs:
  check-version:
    name: Check version number
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: actions/checkout@v4
      - name: Install PyGitHub
        run: python3 -m pip install PyGitHub
      - name: Check version number and make release if necessary
        run: python3 .github/scripts/version.py ${{ secrets.GITHUB_TOKEN }} >> $GITHUB_OUTPUT
        id: version-check

      - name: Trigger Read the Docs build
        run: python .github/scripts/trigger_rtd_build.py ${{ secrets.RTDS_TOKEN }}
        if: steps.version-check.outputs.release != 'no'

      - name: Prepare release
        run: |
          python3 -m pip install build
          python3 -m build .
        if: steps.version-check.outputs.release != 'no'
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.version-check.outputs.release != 'no'
